### ISSUE TITLE
consider splitting factor code into its own function

### ISSUE THREAD

**Issue by fsolt** [sammo3182/interplot#12]
I haven't studied it enough to be sure, but a quick glance looks like the code was repeated across all the subfunctions.  Having the factor code in a separate function would both make it easier to further revise as well as keep the main code more legible.

**Comment by sammo3182** [comment]
Not sure whether it is worth to do so: despite the similarity between 60:74 and 77:90 in `interplot_default.R`, the information of `factor_v2 (or factor_v1) <- TRUE` is critical for later plotting, since the current function has different strategies to deal with factors as a conditioned or conditioning variable (see 141:150 vs. 179:186). In other words, split factor codes into a separate function might produce more problems than efficiency.
